url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Chih-Yuan Yang (楊智淵)" # the name of your site, e.g. ACME Corp.
description: "Assistant Professor at Chang Gung University"
