url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "CGU AICV Lab" # the name of your site, e.g. ACME Corp.
description: "Computer Vision Lab of the Department of Artificial Intelligence at Chang Gung University"
